espoo-dev/the_reef

public/index.html
=> Setting font #1

src/components/Indicator/Indicator.test.tsx, src/components/Indicator/Indicator.tsx
=> :hammer: Refactor tests #5

README.md
=> Adding codeclimate maintainability badge #10

.circleci/config.yml
=> Circleci editor/circleci project setup

README.md
=> :art: Update Readme #14

.circleci/config.yml, README.md, package.json
=> 👷 Adding test coverage report

.circleci/config.yml, README.md, package.json, src/components/Header/Header.test.tsx
=> ✅  Adding test of header

package.json, src/components/Indicator/Indicator.test.tsx, yarn.lock
=> ✅  Adding test to check no danger in Indicator

src/App.test.tsx
=> ✅ Adding app test #21

package.json, src/components/Indicator/Indicator.styles.tsx, src/components/Indicator/Indicator.test.tsx, src/components/Indicator/Indicator.tsx, src/pages/Dashboard/Dashboard.styles.tsx, src/pages/Dashboard/Dashboard.tsx, yarn.lock
=> 👾 Adding icons in indicator 

.circleci/config.yml
Setting reporter id in circle and removing from pipe
fix #32
=> 👷 Removing reporter id  #32

README.md
=> 🎨  Update readme with vercel link and instructions

src/components/Indicator/Indicator.test.tsx, src/index.test.tsx
Removing too screen debug
fix #36
Thanks Edimo!
=> ✅ adding coverage in index #36

src/components/Indicator/Indicator.test.tsx, src/components/Indicator/Indicator.tsx
=> ✨  Adding ideal values to indicator card #38

.circleci/config.yml, .husky/pre-commit, package.json, yarn.lock
=> add-husky-#40

back/src/application/AddFish.ts, back/src/domain/entity/Aquarium.ts, back/src/domain/repository/AquariumRepository.ts, back/src/infra/repository/memory/AquariumRepositoryMemory.ts, back/test/unit/Aqua.test.ts, back/test/unit/integration/AddFish.test.ts
fix #56 
Add get in AquariumRepository and add use case to add fish in aquarium.
=> ✨ Add fish in aquarium #56

back/.eslintignore, back/.eslintrc.json, back/package.json, back/src/application/AddFish.ts, back/src/domain/entity/Aquarium.ts, back/src/domain/entity/Dimensions.ts, back/src/domain/entity/Fish.ts, back/src/domain/repository/AquariumRepository.ts, back/src/infra/database/Connection.ts, back/src/infra/database/PgPromiseConnectionAdapter.ts, back/src/infra/http/ExpressAdapter.ts, back/src/infra/http/Http.ts, back/src/infra/repository/database/AquariumRepositoryDatabase.ts, back/src/infra/repository/memory/AquariumRepositoryMemory.ts, back/src/main.ts, back/test/integration/API.test.ts, back/test/integration/AddFish.test.ts, back/test/integration/AquariumRepositoryDatabase.test.ts, back/test/unit/Aqua.test.ts, back/yarn.lock
=> 🚨 Add ESLint

back/.editorconfig, back/.vscode/settings.json, back/database.sql, back/package.json, back/src/application/AddIndicatorToAquarium.ts, back/src/application/index.ts, back/src/domain/entity/Aquarium.ts, back/src/domain/entity/Indicator.ts, back/src/domain/entity/index.ts, back/src/domain/repository/IndicatorRepository.ts, back/src/domain/repository/index.ts, back/src/infra/repository/database/AquariumRepositoryDatabase.ts, back/src/infra/repository/database/IndicatorRepositoryDatabase.ts, back/test/integration/AddIndicatorToAquarium.test.ts, back/test/integration/IndicatorRepositoryDatabase.test.ts, back/test/unit/Aqua.test.ts, back/test/unit/Indicator.test.ts
=> ✨ Add indicator entity with test result #63

back/package.json, back/src/application/AddIndicatorToAquarium.ts, back/src/domain/factory/RepositoryFactory.ts, back/src/infra/database/PgPromiseConnectionAdapter.ts, back/src/infra/factory/DatabaseRepositoryFactory.ts, back/test/integration/AddIndicatorToAquarium.test.ts, back/yarn.lock
=> 🎇 Add Factory to repositories

hardware/server/server.ino
=> ✨add client hardware code #104

back/test/unit/Fish.test.ts
=> Create fish tests cases

back/src/domain/repository/AquariumRepository.ts, back/src/infra/controller/AquariumController.ts, back/src/infra/repository/database/AquariumRepositoryDatabase.ts, back/src/infra/repository/memory/AquariumRepositoryMemory.ts, back/test/integration/API.test.ts
=> :sparkles: feat: add endpoint to save new aquarium #119

.gitignore, back/database.sql, back/src/domain/entity/Aquarium.ts, back/src/domain/entity/Fan.ts, back/src/domain/repository/FanRepository.ts, back/src/domain/repository/index.ts, back/src/infra/repository/database/FanRepositoryDatabase.ts, back/src/infra/repository/database/index.ts, back/test/integration/FanRepositoryDatabase.test.ts, back/test/unit/Aquarium.test.ts, back/test/unit/Fan.test.ts
=> 🎇 Add fan repository

front/public/index.html, front/src/components/Equipment/Equipment.styles.tsx, front/src/components/Equipment/Equipment.test.tsx, front/src/components/Equipment/Equipment.tsx, front/src/main/theme.ts, front/src/main/types/styled.d.ts, front/src/pages/Dashboard/Dashboard.styles.tsx, front/src/pages/Dashboard/Dashboard.tsx
=> feat: create equipment card status #140 :sparkles:

back/src/infra/controller/FanController.ts, back/src/infra/controller/index.ts, back/src/main.ts, back/test/integration/API.test.ts
=> :sparkles: add new controller to fan #134

back/src/application/UpdateFanOn.ts, back/src/domain/factory/RepositoryFactory.ts, back/src/domain/repository/FanRepository.ts, back/src/infra/controller/FanController.ts, back/src/infra/factory/DatabaseRepositoryFactory.ts, back/src/infra/repository/database/FanRepositoryDatabase.ts, back/src/main.ts, back/test/integration/API.test.ts, back/test/integration/UpdateFanOn.test.ts
=> :sparkles: feat: add new route to update fan to on/off #143

front/src/infra/http/AxiosAdapter.ts, front/src/infra/http/api.ts
=> :sparkles: feat: add put method to axios adapter #145

hardware/server/server.ino
=> improve: remove NTP code from ino and add fan controller #150 :sparkles:

backend_v2/Gemfile, backend_v2/app/models/aquarium.rb, backend_v2/app/models/dimension.rb, backend_v2/app/models/user.rb, backend_v2/db/migrate/20240603194806_create_aquaria.rb, backend_v2/db/migrate/20240603205320_create_dimensions.rb, backend_v2/db/schema.rb, backend_v2/packs/oauth/app/oauth/actors/find_or_create_user.rb, backend_v2/spec/factories/aquaria.rb, backend_v2/spec/factories/dimensions.rb, backend_v2/spec/models/aquarium_spec.rb, backend_v2/spec/models/dimension_spec.rb, backend_v2/spec/models/user_spec.rb
=> [174-backend] Create aquarium and dimension

backend_v2/app/models/aquarium.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/db/migrate/20240608085638_create_on_off_sensors.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/on_off_sensors.rb, backend_v2/spec/models/aquarium_spec.rb, backend_v2/spec/models/on_off_sensor_spec.rb
=> 177: create on_off_sensor

backend_v2/app/models/aquarium.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/app/models/range_sensor.rb, backend_v2/db/migrate/20240608085638_create_on_off_sensors.rb, backend_v2/db/migrate/20240608091409_create_range_sensors.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/on_off_sensors.rb, backend_v2/spec/factories/range_sensors.rb, backend_v2/spec/models/aquarium_spec.rb, backend_v2/spec/models/on_off_sensor_spec.rb, backend_v2/spec/models/range_sensor_spec.rb
=> 181 web server create range sensor

backend_v2/app/models/aquarium.rb, backend_v2/app/models/on_off_actuator.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/db/migrate/20240608094317_create_on_off_actuators.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/on_off_actuators.rb, backend_v2/spec/models/aquarium_spec.rb, backend_v2/spec/models/on_off_actuator_spec.rb, backend_v2/spec/models/range_sensor_spec.rb
=> 183-Create OnOffActuator model with validations and relationships

backend_v2/app/models/current_on_off_value.rb, backend_v2/app/models/on_off_actuator.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/db/migrate/20240608085638_create_on_off_sensors.rb, backend_v2/db/migrate/20240608100106_create_current_on_off_values.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/current_on_off_values.rb, backend_v2/spec/factories/on_off_sensors.rb, backend_v2/spec/models/current_on_off_value_spec.rb, backend_v2/spec/models/on_off_actuator_spec.rb, backend_v2/spec/models/on_off_sensor_spec.rb
=> 185: create current on off value model

backend_v2/app/models/current_numeric_value.rb, backend_v2/app/models/range_sensor.rb, backend_v2/app/policies/application_policy.rb, backend_v2/db/migrate/20240608120409_create_current_numeric_values.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/current_numeric_values.rb, backend_v2/spec/models/current_numeric_value_spec.rb, backend_v2/spec/models/range_sensor_spec.rb
=> 187 web server create current numeric value

backend_v2/app/controllers/admin/aquaria_controller.rb, backend_v2/app/controllers/admin/dimensions_controller.rb, backend_v2/app/controllers/admin/embedded_servers_controller.rb, backend_v2/app/controllers/admin/on_off_actuators_controller.rb, backend_v2/app/controllers/admin/on_off_sensors_controller.rb, backend_v2/app/controllers/admin/on_off_values_controller.rb, backend_v2/app/controllers/admin/range_sensors_controller.rb, backend_v2/app/dashboards/aquarium_dashboard.rb, backend_v2/app/dashboards/dimension_dashboard.rb, backend_v2/app/dashboards/embedded_server_dashboard.rb, backend_v2/app/dashboards/on_off_actuator_dashboard.rb, backend_v2/app/dashboards/on_off_sensor_dashboard.rb, backend_v2/app/dashboards/on_off_value_dashboard.rb, backend_v2/app/dashboards/range_sensor_dashboard.rb, backend_v2/app/serializers/on_off_sensor_serializer.rb, backend_v2/config/routes.rb
=> 191: create dashboard to all models

backend_v2/app/controllers/api/v1/aquaria_controller.rb, backend_v2/app/policies/aquarium_policy.rb, backend_v2/app/serializers/aquarium_serializer.rb, backend_v2/app/serializers/dimension_serializer.rb, backend_v2/app/serializers/embedded_server_serializer.rb, backend_v2/config/routes.rb, backend_v2/spec/factories/aquaria.rb, backend_v2/spec/requests/api/v1/aquaria_request_spec.rb
=> Add endpoint to list user's aquaria

backend_v2/app/contracts/user_contracts/create.rb, backend_v2/app/controllers/api/v1/users_controller.rb, backend_v2/app/dashboards/user_dashboard.rb, backend_v2/app/models/user.rb, backend_v2/app/serializers/on_off_sensor_serializer.rb, backend_v2/config/locales/en.yml, backend_v2/db/migrate/20240611222839_add_name_to_users.rb, backend_v2/db/schema.rb, backend_v2/db/seeds.rb, backend_v2/spec/factories/users.rb, backend_v2/spec/models/user_spec.rb, backend_v2/spec/requests/api/v1/on_off_sensors_request_spec.rb, backend_v2/spec/requests/api/v1/users_request_spec.rb
=> [194 - Web Server] add name to user

backend_v2/app/contracts/range_sensor_contracts/index.rb, backend_v2/app/controllers/admin/numeric_values_controller.rb, backend_v2/app/controllers/api/v1/range_sensors_controller.rb, backend_v2/app/dashboards/numeric_value_dashboard.rb, backend_v2/app/models/range_sensor.rb, backend_v2/app/policies/range_sensor_policy.rb, backend_v2/app/serializers/numeric_value_serializer.rb, backend_v2/app/serializers/range_sensor_serializer.rb, backend_v2/config/routes.rb, backend_v2/spec/factories/range_sensors.rb, backend_v2/spec/requests/api/v1/range_sensors_request_spec.rb
=> 200 add endpoint to list range sensors

backend_v2/app/contracts/on_off_actuator_contracts/index.rb, backend_v2/app/controllers/api/v1/on_off_actuators_controller.rb, backend_v2/app/models/on_off_actuator.rb, backend_v2/app/policies/on_off_actuator_policy.rb, backend_v2/app/serializers/on_off_actuator_serializer.rb, backend_v2/config/routes.rb, backend_v2/db/migrate/20240612224949_update_on_off_actuators_to_make_sensors_optional.rb, backend_v2/db/schema.rb, backend_v2/spec/factories/on_off_actuators.rb, backend_v2/spec/models/on_off_actuator_spec.rb, backend_v2/spec/requests/api/v1/on_off_actuators_request_spec.rb
=> 202: add endpoint to list on off actuatos

backend_v2/.reek.yml, backend_v2/app/models/range_sensor.rb, backend_v2/app/serializers/range_sensor_serializer.rb, backend_v2/spec/models/range_sensor_spec.rb, backend_v2/spec/requests/api/v1/range_sensors_request_spec.rb
=> 204: add extra info to range_sensor

backend_v2/Gemfile, backend_v2/Gemfile.lock, backend_v2/app/models/on_off_actuator.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/app/models/on_off_value.rb, backend_v2/app/policies/on_off_value_policy.rb, backend_v2/app/policies/owner_policy.rb, backend_v2/app/policies/user_policy.rb, backend_v2/spec/factories/users.rb, backend_v2/spec/policies/on_off_value_policy_spec.rb, backend_v2/spec/policies/user_policy_spec.rb, backend_v2/spec/support/pundit_matchers.rb
=> [Web Server] Improve policies and specs

backend_v2/app/controllers/api/embedded/v1/aquaria_controller.rb, backend_v2/app/serializers/embedded_aquarium_serializer.rb, backend_v2/config/routes.rb, backend_v2/spec/requests/embedded/api/v1/aquaria_request_spec.rb
=> [Web Server] Add endpoint to get current aquarium for embedded_server

backend_v2/.rubocop.yml, backend_v2/app/models/numeric_value.rb, backend_v2/app/models/range_sensor.rb, backend_v2/app/serializers/range_sensor_serializer.rb, backend_v2/spec/models/numeric_value_spec.rb, backend_v2/spec/requests/client/api/v1/range_sensors_request_spec.rb
=> [Web Server] Add amount of numeric values outside range from past 24 hours to range sensor

backend_v2/app/models/on_off_sensor.rb, backend_v2/app/models/on_off_value.rb, backend_v2/app/models/range_sensor.rb, backend_v2/app/serializers/on_off_sensor_serializer.rb, backend_v2/app/serializers/range_sensor_serializer.rb, backend_v2/spec/models/on_off_sensor_spec.rb, backend_v2/spec/models/on_off_value_spec.rb, backend_v2/spec/requests/client/api/v1/on_off_sensors_request_spec.rb, backend_v2/spec/requests/client/api/v1/range_sensors_request_spec.rb
=> [Web Server] Add amount of on values from past 24 hours to on off actuator payload

backend_v2/.rubocop.yml, backend_v2/app/models/aquarium.rb, backend_v2/app/models/on_off_sensor.rb, backend_v2/app/models/range_sensor.rb, backend_v2/app/serializers/aquarium_serializer.rb, backend_v2/spec/models/aquarium_spec.rb, backend_v2/spec/models/on_off_sensor_spec.rb, backend_v2/spec/models/range_sensor_spec.rb, backend_v2/spec/requests/client/api/v1/aquaria_request_spec.rb
=> [Web Server] Add warning to aquarium payload
